### ISSUE TITLE
Sloppy ProGuard/R8 rules (consumer-proguard-rules.pro) prevent release build optimizations.

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#106]
The following rule in [consumer-proguard-rules.pro](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/consumer-proguard-rules.pro):

```
-keep class com.launchdarkly.android.** { *; }
```

defeats all the benefits of the code minification/optimizations that R8 provides.

Please provide more specific rules that allow R8 to do its job.

**Comment by gwhelanLD** [comment]
Thanks for the suggestion, I've filed it internally (ch90782) as an enhancement to implement when time is available.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hey @valeriyo,

The release optimization situation should be substantially improved in the [3.0.0 release](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.0.0). Thanks for the suggestion! 

Let us know if you run into any more issues,
@gwhelanLD
