### ISSUE TITLE
Usage: LDClient::close() on application termination unclear

### ISSUE THREAD

**Issue by nwellis** [launchdarkly/android-client-sdk#109]
**Describe the bug**
I'm confused on how to close the LD client from the docs:
> Lastly, when your application is about to terminate, shut down ldClient. This ensures that the client releases any resources it is using, and that any pending analytics events are delivered to LaunchDarkly. If your application quits without this shutdown step, you may not see your requests and users on the dashboard, because they are derived from analytics events. This is something you only need to do once.
https://docs.launchdarkly.com/sdk/client-side/android#getting-started

I think its atypical to listen for application termination as it's not something an application can listen to? Looking at an `Application`'s `onTerminate()` callback the doc states:
```java
    /**
     * This method is for use in emulated process environments.  It will
     * never be called on a production Android device, where processes are
     * removed by simply killing them; no user code (including this callback)
     * is executed when doing so.
     */
    @CallSuper
    public void onTerminate() {
    }
```

The `ProcessLifecycleOwner.java` states something similar. Am I missing something? Is there an example I can reference to help me out in this regard? Thank you for your time!

**SDK version**
2.13.0

**Comment by gwhelanLD** [comment]
Hi @nwellis,

You shouldn't need to monitor the application state and explicitly close the SDK when the application is terminating. If you have a mechanism within your application to explicitly quit, you can call `close()` if you know you will not be using the client again. I've filed this issue internally (ch91372) to improve the documentation to make this more clear. 

Thanks,
@gwhelanLD

**Comment by nwellis** [comment]
I see, that makes a lot of sense. Thank you for your assistance!

**Comment by RyanNewsom** [comment]
@gwhelanLD I had this same confusion, which led me here. Please update your documentation to be more concise.
