### ISSUE TITLE
Please log with one tag, such as "LDClient"

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#113]
Currently, LD library logs using the default tag, based on class name. For example, `DefaultUserManager` has this line:

```
Timber.d("Setting current user to: [%s] [%s]", ..., ...));
```
which shows up in my application as:
```
2020-10-11 18:50:12.612 27847-27847/my.app D/DefaultUserManager: Setting current user to: [...] [...]
```

This is not good. I need to be able to filter out these log lines, because they contain PII, and using "DefaultUserManager" as tag isn't very descriptive - there could be another class with that name in my app. I need to be able to deterministically identify logs by LD (or any other library, for that matter).

So, please make sure that you always specify a library-specific tag when logging:

```
Timber.tag("LDClient").d("Setting current user to: [%s] [%s]", ..., ...));
```
which would result in:
```
2020-10-11 18:50:12.612 27847-27847/my.app D/LDClient: Setting current user to: [...] [...]
```

Thank you.

**Comment by gwhelanLD** [comment]
Hi @valeriyo,

Thanks for another good suggestion. I've filed in internally (ch92277), and we're hoping to get to it soon.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
As of the [3.0.0 release](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.0.0), all logging should include the tag "LaunchDarklySdk". 

Thanks for the suggestion!
@gwhelanLD
