### ISSUE TITLE
Launch Darkly's play services dependency conflicting with latest play services versions

### ISSUE THREAD

**Issue by chrisr-ifit** [launchdarkly/android-client-sdk#121]
**Is your feature request related to a problem? Please describe.**
Our application has a dependency on Launch Darkly and Firebase Crashlytics + Firebase Performance Monitoring.  Launch Darkly has a dependency on a very old version of play services, [here](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/build.gradle#L77), that is conflicting with our Firebase dependency, which uses the latest play services version of `4.3.5`.

**Describe the solution you'd like**
Ideally Launch Darkly could update it's dependency of play services to allow the consumer opt-in or opt-out, based on their needs, this concept is proven in this [PR](https://github.com/launchdarkly/android-client-sdk/pull/120).  My understanding is Launch Darkly only has this dependency for older Android OS support.

**Describe alternatives you've considered**
Launch Darkly could remove the dependency of play services, or upgrade to the latest version.

**Additional context**
None.

**Comment by bwoskow-ld** [comment]
Hi @chrisr-ifit,

Our upcoming version 3.0.0 of this SDK will obviate this issue by no longer depending on Google Play Services. We'll keep this issue open until 3.0.0 is available. Stay tuned -- we'll notify you soon here when it is available.

Cheers,
@bwoskow-ld

**Comment by gwhelanLD** [comment]
The [3.0.0 release](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.0.0) is now available. 

Thanks for the patience,
@gwhelanLD
