### ISSUE TITLE
Don't force consumers to use Gson (please)

### ISSUE THREAD

**Issue by JvmName** [launchdarkly/android-client-sdk#122]
Hi LD team!
I understand that y'all want to own your own JSON+networking stack -- and since app size isn't an issue for us, y'all bundling Gson for internal networking purposes is not a huge deal. But what _is_ an issue is that there are a number of APIs that require a `com.google.gson.JsonElement` -- e.g. `track(String, JsonElement)`, or `jsonVariation(String, JsonElement) : JsonElement`.

If I want to pull a JSON blob, or pass info to LD, I have to add Gson to my classpath! Which is a bummer, since my app uses Moshi through and through 😁 

I recognize this would be a breaking change, here's the request - can you please scrub any Gson classes from the public API? Let me pass a `Map<String, Any>` to `track`, and have `jsonVariation` give me a `String?` instead. 

Thank for hearing me out!

**Comment by eli-darkly** [comment]
That's already in the works, with a somewhat different implementation than you proposed. Our upcoming Android SDK 3.0 will be removing Gson from the public API, just as our [Java SDK 5.0](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.0.0) did. Everything in the API that currently uses `JsonElement` will instead use a new immutable JSON data type that belongs to the SDK, [`LDValue`](https://javadoc.io/doc/com.launchdarkly/launchdarkly-java-server-sdk/latest/com/launchdarkly/sdk/LDValue.html).

**Comment by eli-darkly** [comment]
As a side note, the data you pass to `track` doesn't have to be a JSON _object_ value (as your use of `Map` suggests)— it can be any valid JSON value.

**Comment by JvmName** [comment]
Hey that's great to hear! Is there a rough timeline y'all are planning for release (Q2? Q3?)?

**Comment by eli-darkly** [comment]
I don't know the details of the release plan and I think we generally avoid saying more than a _very_ rough estimate— I'll defer to @bwoskow-ld on that question. I do know that it's been under active development for a while and we've already done much of the planned work that I was aware of.

**Comment by JvmName** [comment]
What a small world, I know @bwoskow-ld from many moons ago at Atlassian 👋🏽

I'd be happy with a very rough estimate, if y'all are comfortable!

**Comment by eli-darkly** [comment]
Lots of ex-Atlassians at LD - I was too, but maybe not at that time. Anyway, I'll check in with Ben on Monday.

**Comment by bwoskow-ld** [comment]
Hi, @JvmName! Nice to see your face around here 😄  You two overlapped at Atlassian in terms of your tenures but not in what you were working on.

Anyways -- we're getting very close to the aforementioned release. It'll be available sooner than later. I know that my mentioned timeframe isn't concrete, but my intended takeaway here is for you to know that you'll be able to drop the Gson dependency "pretty soon". We'll update this ticket when the new release is available.

**Comment by JvmName** [comment]
Sounds good, appreciate the update Ben!

**Comment by gwhelanLD** [comment]
Hi @JvmName,

I'm happy to let you know the new [3.0.0 release](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.0.0) should let you take advantage of all the SDK functionality without touching `Gson`!

Thanks,
@gwhelanLD
