### ISSUE TITLE
Explicitly specify `android:exported` for every component in manifest

### ISSUE THREAD

**Issue by elliemehrganrad** [launchdarkly/android-client-sdk#128]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
As one of the changes on apps targeting Android 12, it is forced to explicitly specify android:exported for every components containing `intent-filter` in manifest.

Targeting Android 12 we get manifest merge conflict caused by launchdarkly SDK: `com.launchdarkly:launchdarkly-android-client-sdk:3.0.0`

**To reproduce**

1. Project with launchdarkly SDK 3.0.0
2. Change compileSdkVersion to 'android-S' and targetSdkVerrsion to 'S'
3. Build the project
4. Attempt to install to a device/emulator with Android S preview

**Expected behavior**

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
3.0.0

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
Android 12

**Additional context**
Tested on Google Pixel 4a emulator

**Comment by gwhelanLD** [comment]
Hi @elliemehrganrad,

Thanks for bringing this Android change to our attention so we can address it prior to the official Android S release. I've filed it internal as something to address. 

Thanks,
@gwhelanLD

**Comment by elliemehrganrad** [comment]
> Hi @elliemehrganrad,
> 
> Thanks for bringing this Android change to our attention so we can address it prior to the official Android S release. I've filed it internal as something to address.
> 
> Thanks,
> @gwhelanLD

Hi @gwhelanLD,

Thank you for your reply. 
I would appreciate it if you could let me know whenever the new version is rolled out.
Thanks in advance.

@elliemehrganrad

**Comment by gwhelanLD** [comment]
Hi @elliemehrganrad,

This should be resolved now with the 3.0.1 release. Thanks for bringing this issue to our attention!

Thanks,
@gwhelanLD

**Comment by elliemehrganrad** [comment]
Hi @gwhelanLD,

Thanks for letting me know.

@elliemehrganrad
