### ISSUE TITLE
Please update Timber version to avoid  "Using "'Log' instead of 'Timber'" Danger error."

### ISSUE THREAD

**Issue by YvgenTroshchiy** [launchdarkly/android-client-sdk#140]
Found that when we added `launchdarkly` to our project we've started observe new errors:
```Using "'Log' instead of 'Timber'" Danger error.```
But we didn't have `Timber` in our project.
After run dependency check I've found that launchdarkly contains timber.

|    |    |    |    |    |         +--- com.launchdarkly:**launchdarkly**-android-client-sdk:2.14.2
|    |    |    |    |    |         |    +--- com.google.code.gson:gson:2.8.2 -> 2.8.6
|    |    |    |    |    |         |    +--- com.launchdarkly:okhttp-eventsource:1.8.0
|    |    |    |    |    |         |    |    +--- com.squareup.okhttp3:okhttp:3.8.1 -> 3.14.7 (*)
|    |    |    |    |    |         |    |    +--- org.slf4j:slf4j-api:1.7.22 -> 1.7.25
|    |    |    |    |    |         |    |    \--- com.google.code.findbugs:jsr305:3.0.2
|    |    |    |    |    |         |    +--- com.squareup.okhttp3:okhttp:3.12.2 -> 3.14.7 (*)
|    |    |    |    |    |         |    +--- com.jakewharton.**timber**:timber:4.7.1

And there is issue in Timber that was already fixed https://github.com/JakeWharton/timber/issues/380

After I've added latest timber version `implementation 'com.jakewharton.timber:timber:5.0.1'`
This errors disapears.
```Using "'Log' instead of 'Timber'" Danger error.```

Unfortunately I can't create a PR. Because of
```
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by bwoskow-ld** [comment]
Hi @YvgenTroshchiy ,

We accept pull requests from forked repositories. While you don't have direct write access on this repository, you're welcome to fork the repository to your own account, push your changes to a branch on your fork, and then submit a pull request from there to here. From there we can review and consider your changes.

Cheers,
@bwoskow-ld

**Comment by YvgenTroshchiy** [comment]
Got it, thank you for the explanation. Created https://github.com/launchdarkly/android-client-sdk/pull/141
