### ISSUE TITLE
How to avoid conflicts between LD's Timber logs and our own app's Timber logs?

### ISSUE THREAD

**Issue by erawhctim** [launchdarkly/android-client-sdk#147]
**Is your feature request related to a problem? Please describe.**
Our app uses Timber for logging, and have a custom `Tree` that sends exceptions from `Timber.w()` and `Timber.e()` calls into our error reporting system. Our team noticed some strange errors in our system and eventually realized that these were originating within the LD SDK ([Here's one example](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/StreamUpdateProcessor.java#L87), ultimately resulting from the Timber usage in `LDConfig` [here](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDConfig.java#L30-L31)). 

How should we avoid the discrepancy between LD's own Timber logging `Tree` and our own?

**Describe the solution you'd like**
There's a few different solutions that come to mind. I'm curious if you all have thoughts on _any_ of them, or if anyone else has run into a similar issue?
- Preferably, LD would use its own logging abstraction and minimize its 3rd party dependencies (but Timber is useful so I see the benefit of using it). LD could also pull in the Timber class files themselves and include them in the SDK (but renamed) to avoid the conflict.
  - We could also do the example same thing on our side, which is equally reasonable.
- We could update our custom Timber `Tree` to try and ignore logs that originated from Trees that we don't own. 

**Describe alternatives you've considered**
Logging within our app via a completely different method (which we're not opposed to).

**Additional context**
N/A

**Comment by louis-launchdarkly** [comment]
Hello @erawhctim, thank you for reaching out. We are looking into abstracting the logging layer and the task is on our backlog.

Filed Internally as 45759.

**Comment by erawhctim** [comment]
Great, thanks Louis! 
Do you have an ballpark estimate on when that work will start/finish/etc? Or is it too soon to know?

**Comment by louis-launchdarkly** [comment]
Right, it is too soon for us to have an estimate on timing, as this change looks pretty big.

**Comment by gwhelanLD** [comment]
Hi @erawhctim,

We've started on a logging interface for the SDK to allow configuration and alternative logging backends, but aren't able to give a timeline on completing that work at the moment. One detail that may be helpful for filtering the logs the SDK records with Timber currently is that all log statements are tagged "LaunchDarklySDK" (see [here](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/sdk/android/LDConfig.java#L30-L31)).

Thanks,
@gwhelanLD

**Comment by erawhctim** [comment]
That's exactly what I was looking for - thank you @gwhelanLD!

**Comment by eli-darkly** [comment]
We've released version 3.2.0, which retains the current default Timber behavior but makes it possible to specify different behavior or disable logging. Please see [this comment](https://github.com/launchdarkly/android-client-sdk/issues/88#issuecomment-1224949414) and the changelog.
