### ISSUE TITLE
Application Name is overridden

### ISSUE THREAD

**Issue by Exaper** [launchdarkly/android-client-sdk#155]
**Describe the bug**
SDK overrides application name string

**To reproduce**
Integrate the SDK. Notice <string name="app_name">launchdarkly-android-client-sdk</string>

**Expected behavior**
SDK should not contain application name.

**SDK version**
3.1.1

**Additional context**
Just remove the "app_name" string. SDK should not contain it (refer to other mature SDKs out there). Alternatively, rename `app_name` resource to something else like `ld_app_name` or `launch_darkly_app_name`.

**Comment by louis-launchdarkly** [comment]
Hello @Exaper, thank you for the contribution. The change you made seems good - we will test the change and if there is nothing else, we will merge your change for the next release. So I will close this issue and continue update in the PR.
