### ISSUE TITLE
Is it `doubleVariation` or `floatVariation`?

### ISSUE THREAD

**Issue by byencho** [launchdarkly/android-client-sdk#159]
The 3.0.0 CHANGELOG entry makes the following claims:

- `floatVariation` and `floatVariationDetail` have been changed to have the same behavior as the removed `doubleVariation` and `doubleVariationDetail`.
- `doubleVariation` and `doubleVariationDetail` have been removed. Use `floatVariation` and `floatVariationDetail` instead.

When using the SDK with versions 3.0.0+, it is clear, though, that `doubleVariation` exists and `floatVariation` does not. You can also search the current codebase to see [many references](https://github.com/launchdarkly/android-client-sdk/search?q=doubleVariation) to `doubleVariation` but the [only references](https://github.com/launchdarkly/android-client-sdk/search?q=floatVariation) to `floatVariation` are in the CHANGELOG.

Is this simply a mistake in the documentation?

**Comment by eli-darkly** [comment]
It's a mistake in the changelog— the names were simply reversed. That is, `floatVariation` existed in older versions, but this was inconsistent with all other LaunchDarkly SDKs and the product itself, which use double-precision floating point rather than single-precision for all numbers. So it's been standardized on double.

**Comment by byencho** [comment]
@eli-darkly OK good to know, thanks! Do you think it would be possible to correct the CHANGELOG then so that anyone looking at it now can get a better sense of the current state of the code?

**Comment by louis-launchdarkly** [comment]
Hello @byencho, we have fixed the CHANGELOG just now. Thank you for reporting the issue to us!

**Comment by byencho** [comment]
Excellent, thanks!
