### ISSUE TITLE
Notice: For the ANR fix that we are preparing to release today (29th July).

### ISSUE THREAD

**Issue by louis-launchdarkly** [launchdarkly/android-client-sdk#174]
While we finished the change in the private repo, we had an issue running the SDK with the internal integration test and were only able to verify the change now. I am sorry that we are not able to cut the release today. I know multiple people are waiting for this fix, and we will cut the release for this on Monday (1st August).

**Comment by aengelberg** [comment]
We've addressed the issues in our release pipeline, and the release ([3.1.6](https://github.com/launchdarkly/android-client-sdk/releases/tag/3.1.6)) is now out.
