### ISSUE TITLE
SDK returns true for the flag even if default value is false and value in console is false as well

### ISSUE THREAD

**Issue by Holoceo** [launchdarkly/android-client-sdk#192]
**Describe the bug**
1. Flag default value is false
2. Flag value in launchdarkly console is false
3. Flag value is being read before **identify** is called
4. SDK return **true** for that flag

**Expected behavior**
Flag returns false

**SDK version**
3.2.1

**OS/platform**
Android

**Additional context**
Feel free to reach me. I can demonstrate it live or record a video.

**Comment by eli-darkly** [comment]
The best channel for contacting someone at LD, if you might need to share any non-public information, would be support.launchdarkly.com. They may end up reaching out to me here on the SDK team anyway, but we can't really tell whether this is in fact an Android SDK issue, or some other kind of service issue, until we're able to look at the data in your account.

Besides the information you've already provided, it would be good to tell them:
* the mobile key you're using
* the (non-mobile) SDK key that corresponds to the same environment
* the flag key
* if possible, a sample of the code where you are getting the flag value
* whether there have been any recent changes to the value of the flag (i.e. was it true in the past)

**Comment by eli-darkly** [comment]
I'm inclined to think that whatever is going wrong is probably not within the Android SDK, just because I can't think of any mechanism for it to make up a true value when there wasn't one; the SDK's logic for providing flag values is very simple, it always returns either a value it received from LaunchDarkly or else the default value parameter that you passed to `boolVariation`. But, again, looking at your account data will help us to determine that.

**Comment by Holoceo** [comment]
> I'm inclined to think that whatever is going wrong is probably not within the Android SDK, just because I can't think of any mechanism for it to make up a true value when there wasn't one; the SDK's logic for providing flag values is very simple, it always returns either a value it received from LaunchDarkly, or the default value parameter that you passed to `boolVariation`, or in some cases there could be a cached value from a previous launch of the application if it hasn't yet been able to reach LaunchDarkly this time. But, again, looking at your account data will help us to determine that.

I'm able to demo you the issue if you want. Or provide any data needed.

**Comment by eli-darkly** [comment]
@Holoceo I don't know if you have already filed a support ticket with support.launchdarkly.com, but if not, I really recommend that you do so. A GitHub issue is not a good forum for debugging a problem that is specific to one customer account; you're not talking to the support team here, but rather the maintainers of the SDK code.

**Comment by louis-launchdarkly** [comment]
@Holoceo To follow up on this, were you able to get help through the Support ticket with support.launchdarkly.com?

**Comment by louis-launchdarkly** [comment]
No response for more than half a year, closing this out.
