### ISSUE TITLE
DiagnosticEventProcessor.startScheduler causing OOM on certain devices

### ISSUE THREAD

**Issue by repl-saijanani-s** [launchdarkly/android-client-sdk#210]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/11546108/221641429-f12d14ea-2c0b-4a58-9851-7357a6363a03.png">

**SDK version**
3.1.1

Happened on different devices and different OS versions from Android 9-13 for multiple users.

**Comment by louis-launchdarkly** [comment]
Hello @repl-saijanani-s, thank you for reporting the issue to us.

I have a couple of follow-up questions for you on this one - Do you see this error for any later Android versions? Also, do you see any thread-related errors that happen with `EventProcessor.start()`? The name sounds similar but this one is for the analytics events that drive features you can use in LaunchDarklyUI. My suspicion is that older Android doesn't have enough memory for the few separate threads that the SDK allocates.

In terms of suggestions in the meantime, we recommend migrating to the latest Android 4.x SDK, and if you cannot migrate yet, you can turn off diagnostic events via SDK configuration. Turning diagnostic events off will not affect functionality in your LaunchDarkly UI.

Keeping track of this internally with 190650.
