### ISSUE TITLE
registerAllFlagsListener is not working in 4.2.0

### ISSUE THREAD

**Issue by amit3vedi** [launchdarkly/android-client-sdk#212]
**Describe the bug**
while migrating from version 3.2.3 to latest version 4.2.0 i've noticed that registerAllFlagsListener is not invoking whenever i update feature flag status from launch darkly console. this is working fine on SDK version 3.2.3.

**To reproduce**
- set registerAllFlagsListener after client initialisation.
- Update any flag value on launch darkly console and save it
- registerAllFlagsListener will not invoke on app side.

**Expected behavior**
registerAllFlagsListener should invoke whenever there is any feature flag updates received.

**SDK version**
4.2.0

**OS/platform**
Android 13

**Comment by louis-launchdarkly** [comment]
Hello @amit3vedi, thank you for reporting the issue, we will investigate it and get back to you.

Filed Internally as 191967.

**Comment by roryf** [comment]
Also experiencing this issue. Confirmed using `registerFeatureFlagListener` partially solves it, however we are not getting expected flag values when changing context via `identify` so wonder if there is a problem there also?

**Comment by roryf** [comment]
This is currently blocking our upgrade to RN 0.71 😢

**Comment by tanderson-ld** [comment]
Thank you for reporting this issue @amit3vedi .  We have fixed this in version 4.2.1 which was just released.  Please let us know if you still encounter any issues with `registerFeatureFlagListener`.

**Comment by tanderson-ld** [comment]
@roryf , we will be making an update to our [React Native repo](https://github.com/launchdarkly/react-native-client-sdk) soon to address this issue there as well.

**Comment by roryf** [comment]
Thanks @tanderson-ld, confirmed issue fixed when I patch the RN library to use version 4.2.1.

I think the issue I mentioned above around `identify` was due to introduction of contexts, was previously sending custom attributes in a `custom` user prop, removing that with latest version has fixed it.
