### ISSUE TITLE
LaunchDarkly communication with Organization Own Service for feature flag evaluation

### ISSUE THREAD

**Issue by vballem** [launchdarkly/android-client-sdk#233]
**Is your feature request related to a problem? Please describe.**
I would like LD directly communicates with my own organization service for feature flag evaluation for some flags. 

**Describe the solution you'd like**
I want LD to ask my own service for feature flag evaluation as such LD should able to use my service securely 

**Describe alternatives you've considered**

**Additional context**
[Please refer here.](https://stackoverflow.com/questions/77984830/can-launchdarkly-internally-communicates-with-organizations-external-service-fo)

**Comment by tanderson-ld** [comment]
Hi @vballem, thank you for reaching out.  To get the best answer, please reach out to our support team by following [this link](https://support.launchdarkly.com/hc/en-us/requests/new).
