### ISSUE TITLE
ClassCastException when calling LDClient.init

### ISSUE THREAD

**Issue by jclaudino** [launchdarkly/android-client-sdk#74]
**Describe the bug**
We're getting another class cast exception, this time from the LDClient.init call. 

**To reproduce**
Steps to reproduce the behavior.
Migrate from an older version to a newer version cached flags

**Expected behavior**
Don't crash

**Logs**
Caused by: java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
        at com.launchdarkly.android.Migration.migrate_2_7_fresh(Migration.java:78)
        at com.launchdarkly.android.Migration.migrateWhenNeeded(Migration.java:32)
        at com.launchdarkly.android.LDClient.init(LDClient.java:129)
        at com.launchdarkly.android.LDClient.init(LDClient.java:177)

**SDK version**
2.7.0

**Language version, developer tools**
Kotlin

**OS/platform**
Android, all versions

**Additional context**
```
        try {
            LDClient.get().identify(ldUser)
        } catch (e: LaunchDarklyException) {
            LDClient.init(application, ldConfig, ldUser, 0)
        }
```
It's happening when identify throws an exception that we catch, and then init throws the classcastexception. We've had this code for over a year, but it just now started causing this issue.

**Comment by gwhelanLD** [comment]
Hi @jclaudino,

Thanks for filing an issue about this exception. Your previous issue was very helpful in understanding this issue as well.

We'll get a `2.8.3` patch out shortly with a fix for this issue.

Thanks,
@gwhelanLD

**Comment by gwhelanLD** [comment]
Hi @jclaudino,

We've just release the `2.8.3` patch with a fix for migrations from early versions of the SDK that stored versions without additional fields as JSON objects. Please note that the published artifact id changed in [Release 2.8.1](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.8.1), follow the link for more info. 

Thanks for filing this issue, let us know if you run into any more issues.

Thanks,
@gwhelanLD

**Comment by jclaudino** [comment]
Thanks!!
-Julian

**Comment by gwhelanLD** [comment]
Closing this issue as the patch is out. Feel free to reopen if you run into any more issues.

Thanks,
@gwhelanLD
