### ISSUE TITLE
Crash with launchDarkly 2.7.0

### ISSUE THREAD

**Issue by mbernier85** [launchdarkly/android-client-sdk#80]
**Describe the bug**
App is crashing on launch

**To reproduce**
This happens in production only for now

**Expected behavior**
Not crash ...

**Logs**
```
Caused by java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.String
       at com.launchdarkly.android.Migration.migrate_2_7_fresh + 78(Migration.java:78)
       at com.launchdarkly.android.Migration.migrateWhenNeeded + 32(Migration.java:32)
       at com.launchdarkly.android.LDClient.init + 129(LDClient.java:129)
```
**SDK version**
2.5.4 to 2.7.0

**Language version, developer tools**
Java/kotlin

**OS/platform**
Android 9

**Comment by bwoskow-ld** [comment]
Hi mbernier85,

Thanks for reporting this. This is a [known issue](https://github.com/launchdarkly/android-client-sdk/issues/74) with your version of the SDK. Version 2.8.3 contains a fix for the issue. Please note that the published artifact id changed in [Release 2.8.1](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.8.1) -- follow the link for more info.

Cheers,
Ben
