### ISSUE TITLE
`identify()` future may not complete if device is backgrounded during the call

### ISSUE THREAD

**Issue by gwhelanLD** [launchdarkly/android-client-sdk#91]
Are you sure it's correctly fixed? I'm facing a similar issue with 2.9.0. 

I basically have wrapped all LD interactions in Rx streams. And at some point it involves having `identify` calls running on a specific (non-main) thread. 

But if the app goes into the background when `identify()` is being called, the call is [cancelled](https://github.com/launchdarkly/okhttp-eventsource/blob/master/src/main/java/com/launchdarkly/eventsource/EventSource.java#L191), the event, the connection is [shut down](https://github.com/launchdarkly/okhttp-eventsource/blob/master/src/main/java/com/launchdarkly/eventsource/EventSource.java#L278)

And `identify().get()` will never return, no matter if I retry it after a timeout.

I had to downgrade to `2.7.0` to have it work as expected.

_Originally posted by @drommk in https://github.com/launchdarkly/android-client-sdk/issues/86#issuecomment-555067351_

**Comment by gwhelanLD** [comment]
@drommk,

We'll investigate this issue and try to replicate. Any more specific info on your Rx streams involved in the interactions with the LaunchDarkly Android SDK may be helpful in tracking the issue down. 

Thanks,
@gwhelanLD

**Comment by bwoskow-ld** [comment]
_Filed internally as 62120_

**Comment by gwhelanLD** [comment]
Hi @drommk,

We revisited the completion cases of the Future returned by the `init` and `identify` for the [2.11.0](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.11.0) release and improved our test coverage of this area. Hopefully the changes should address your difficulties with the completion of the Future. I'm closing this issue as I believe we have addressed the cases that could lead to the cases you described, but feel free to reopen if you run into the same issue.

Thanks,
@gwhelanLD
