### ISSUE TITLE
Put your HTTP cache into a subdirectory, Thanks.

### ISSUE THREAD

**Issue by valeriyo** [launchdarkly/android-client-sdk#93]
**Describe the bug**
When I look in the /data/data/my.app.id/cache directory - there is a bunch of files along with "journal" -- which refer to launchdarkly services (e.g. https://app.launchdarkly.com/msdk/...). Most applications use this "cache" directory for many things, and an SDK shouldn't crap all over it.

**To reproduce**
Just run an app with the launchdarkly SDK, then look inside the /data/data/my.app.id/cache directory with Android Studio's Device File Explorer.

**Expected behavior**
The HTTP cache that launchdarkly creates should go into a subdirectory, named appropriately, to avoid name conflicts.. For example: "com.launchdarkly.http_cache"

**SDK version**
2.9.1

<img width="680" alt="LaunchDarklyCacheFiles" src="https://user-images.githubusercontent.com/7052801/73165962-bb0c0800-40a9-11ea-9537-dcddcdb949fc.png">

**Comment by gwhelanLD** [comment]
Hi @valeriyo,

These files are created by OkHttp. Other than `journal` all the file names are generated through hashes that will prevent any name conflicts. Given the extensive use of OkHttp `journal` should likely be considered reserved by it and there should be no issue with multiple OkHttp instances using the same journal, it should actually reduce the overall overhead on the cache. 

Thanks,
@gwhelanLD

**Comment by valeriyo** [comment]
Please keep your own cache to yourself, and configure its limit to whatever you think is reasonable. There is absolutely no benefit for sharing launchdarkly cache with the rest of the application, only possible conflicts and issues.

**Comment by gwhelanLD** [comment]
I've filled this issue in our internal issue tracker (ch63444) so we can schedule time to address it.

Thanks,
@gwhelanLD

**Comment by valeriyo** [comment]
Thank you

**Comment by gwhelanLD** [comment]
@valeriyo,

The fix for this is out in the [2.12.0](https://github.com/launchdarkly/android-client-sdk/releases/tag/2.12.0) release.

Thanks for your suggestion,
@gwhelanLD
