### ISSUE TITLE
Attempted to get non-existent flag for key

### ISSUE THREAD

**Issue by gpeal** [launchdarkly/android-client-sdk#96]
**Describe the bug**
We started seeing tons of logs complaining about `Attempted to get non-existent flag for key` which originates from [this line](https://github.com/launchdarkly/android-client-sdk/blob/master/launchdarkly-android-client-sdk/src/main/java/com/launchdarkly/android/LDClient.java#L373).
It is unclear to me why this is happening. The flags exist on the environment and when I target the device in test, it correctly gets set to true despite the library saying that the flag doesn't exist upon startup.
To make matters stranger, this seems to only happen on some environments which, other than by name, are identical in setting.

**To reproduce**
Start up the app and check logcat. We have websockets enabled on our project.

**Expected behavior**
Launch Darkly doesn't complain about `Attempted to get non-existent flag for key`

**SDK version**
2.10.0

**OS/platform**
Tested on API 23 and 29

**Comment by gwhelanLD** [comment]
Hi @gpeal,

To look into this issue further, we recommend that you file a support request by emailing support@launchdarkly.com. This issue tracker is intended for SDK bug reports and feature requests, and this issue sounds more like a support request. Our support team can look into your environments specifically to try to assist you. 

Hope this helps,
@gwhelanLD
